markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Deep Metric Learning
description: An exploration into contrastive and triplet deep metric learning methods